//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public Assignment()
        {
            this.SubmitedAssignments = new HashSet<SubmitedAssignment>();
        }
    
        public int assignmentId { get; set; }
        public string assignmrtName { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public Nullable<int> courseId { get; set; }
    
        public virtual ICollection<SubmitedAssignment> SubmitedAssignments { get; set; }
    }
}
