//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.EnrolledCourses = new HashSet<EnrolledCours>();
            this.Exams = new HashSet<Exam>();
        }
    
        public int courseId { get; set; }
        public string courseName { get; set; }
        public string catagoryName { get; set; }
    
        public virtual ICollection<EnrolledCours> EnrolledCourses { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
    }
}
