//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int feedBackId { get; set; }
        public Nullable<int> userId { get; set; }
        public string feedBack1 { get; set; }
        public Nullable<System.DateTime> feedBackDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
