//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.EnrolledCourses = new HashSet<EnrolledCours>();
            this.Results = new HashSet<Result>();
            this.SubmitedAssignments = new HashSet<SubmitedAssignment>();
        }
    
        public int studentId { get; set; }
        public Nullable<int> userId { get; set; }
        public string address { get; set; }
        public string @class { get; set; }
    
        public virtual ICollection<EnrolledCours> EnrolledCourses { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SubmitedAssignment> SubmitedAssignments { get; set; }
    }
}
