//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FeedBacks = new HashSet<FeedBack>();
        }
    
        public int userId { get; set; }
        public string name { get; set; }
        public string telephone { get; set; }
        public string pwd { get; set; }
    
        public virtual Alumini Alumini { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
        public virtual Student Student { get; set; }
    }
}
